import { useMemo, useState } from "react";
import { Link, createFileRoute, useNavigate } from "@tanstack/react-router";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, BrainCircuit, CheckCircle2, CircleAlert, Database, FlaskConical, Gauge, ShieldAlert, Sparkles } from "lucide-react";
import { analyzeMatch, loadFreeFixtures, type IntelligenceResult, type MatchRow } from "@/lib/gfi/intelligence";
import { buildMatchReasoning, type MatchReasoning } from "@/lib/gfi/reasoning";
import { savePrediction } from "@/lib/gfi/workbench";

export const Route = createFileRoute("/match/$matchId")({ component: MatchIntelligence });
type Fixture = MatchRow & { league: string; code: string };

function MatchIntelligence() {
  const { matchId } = Route.useParams();
  const navigate = useNavigate();
  const [tab, setTab] = useState<"overview" | "engines" | "evidence" | "reasoning">("overview");
  const [saved, setSaved] = useState(false);
  const query = useQuery({ queryKey: ["free-fixtures", "match-intelligence"], queryFn: loadFreeFixtures, staleTime: 30 * 60_000 });
  const fixture = useMemo(() => { const [home, away, date] = decodeURIComponent(matchId).split("__"); return (query.data ?? []).flatMap(g => g.matches.map(m => ({ ...m, league: g.league, code: g.code }))).find(m => m.home === home && m.away === away && m.date === date) as Fixture | undefined; }, [query.data, matchId]);
  const allMatches = useMemo(() => query.data?.find(g => g.code === fixture?.code)?.matches ?? [], [query.data, fixture?.code]);
  const result = useMemo(() => fixture ? analyzeMatch(fixture, allMatches) : null, [fixture, allMatches]);
  const reasoning = useMemo(() => fixture && result ? buildMatchReasoning(fixture, result) : null, [fixture, result]);

  if (query.isLoading) return <State title="Loading match intelligence" text="Ingesting the free historical evidence layer…" />;
  if (!fixture || !result || !reasoning) return <State title="Match not found" text="The fixture is not available in the current free feed." back />;

  const save = () => { savePrediction({ fixture: { ...fixture, result: fixture.result }, probabilities: result.probabilities, totals: result.totals, btts: result.btts, verdict: reasoning.decision, confidence: result.confidence, quality: result.quality, modelVersion: "free-v1" }); setSaved(true); };

  return <div className="min-h-screen">
    <header className="border-b border-border bg-background/90 px-5 py-5 backdrop-blur lg:px-10"><div className="mx-auto max-w-7xl">
      <button onClick={() => navigate({ to: "/" })} className="label-xs inline-flex items-center gap-2 text-muted-foreground hover:text-foreground"><ArrowLeft className="size-3" /> Back to search</button>
      <div className="mt-6 flex flex-col gap-5 lg:flex-row lg:items-end lg:justify-between"><div><div className="label-xs text-primary">{fixture.league} · MATCH INTELLIGENCE</div><h1 className="mt-2 text-3xl font-semibold tracking-tight">{fixture.home} <span className="text-muted-foreground">vs</span> {fixture.away}</h1><p className="mt-2 text-sm text-muted-foreground">{fixture.date || "Scheduled fixture"} · Authoritative quantitative dossier · FREE MODE</p></div><div className="flex flex-wrap gap-2"><Link to="/simulation" className="button-secondary"><FlaskConical className="size-4" /> Simulate</Link><button onClick={save} className="button-primary"><Database className="size-4" /> {saved ? "Saved to ledger" : "Save prediction"}</button></div></div>
    </div></header>
    <main className="mx-auto max-w-7xl px-5 py-6 lg:px-10">
      <section className="grid gap-3 lg:grid-cols-[1.35fr_1fr_1fr_1fr]"><DecisionCard reasoning={reasoning}/><Metric label="Home" value={`${Math.round(result.probabilities.home*100)}%`} sub="1X2 probability"/><Metric label="Draw" value={`${Math.round(result.probabilities.draw*100)}%`} sub="1X2 probability"/><Metric label="Away" value={`${Math.round(result.probabilities.away*100)}%`} sub="1X2 probability"/></section>
      <div className="mt-6 grid gap-6 lg:grid-cols-[1fr_320px]"><section className="panel overflow-hidden"><div className="flex gap-1 border-b border-border p-2">{(["overview","engines","evidence","reasoning"] as const).map(x => <button key={x} onClick={() => setTab(x)} className={`rounded px-3 py-2 text-xs font-medium ${tab===x ? "bg-elevated text-foreground" : "text-muted-foreground hover:text-foreground"}`}>{x}</button>)}</div><div className="p-5">{tab==="overview" && <Overview result={result}/>} {tab==="engines" && <Engines result={result}/>} {tab==="evidence" && <Evidence result={result}/>} {tab==="reasoning" && <Reasoning reasoning={reasoning}/>}</div></section>
        <aside className="space-y-3"><div className="panel p-5"><div className="flex items-center gap-2"><Gauge className="size-4 text-primary"/><span className="label-xs">MODEL QUALITY</span></div><div className="mt-3 text-3xl font-semibold">{result.quality}</div><div className="mt-1 text-xs text-muted-foreground">Confidence {result.confidence}%</div><div className="mt-4 h-1.5 rounded-full bg-muted"><div className="h-full rounded-full bg-primary" style={{width:`${result.quality}%`}}/></div></div>
          <div className="panel p-5"><div className="flex items-center gap-2"><BrainCircuit className="size-4 text-primary"/><span className="label-xs">AI REASONING LAYER</span></div><p className="mt-3 text-sm leading-6 text-muted-foreground">The reasoning layer receives the structured evidence packet from the engines. A future LLM can synthesize it, but cannot create missing facts or override hard evidence.</p><div className="mt-4 rounded-md border border-border bg-muted/30 p-3 text-xs">{reasoning.claims.filter(c=>c.signal==="SUPPORT").length} supporting · {reasoning.claims.filter(c=>c.signal==="CONTRADICTION").length} contradictions · {reasoning.claims.filter(c=>c.signal==="LIMITATION").length} limitations</div></div>
          <div className="panel p-5"><div className="flex items-center gap-2"><ShieldAlert className="size-4 text-warning"/><span className="label-xs">KNOWN LIMITS</span></div>{result.warnings.map(w=><p key={w} className="mt-3 text-xs leading-5 text-muted-foreground">{w}</p>)}</div></aside>
      </div>
    </main>
  </div>;
}

function DecisionCard({reasoning}:{reasoning:MatchReasoning}){const Icon=reasoning.decision.includes("INSUFFICIENT")||reasoning.decision.includes("CONFLICT")?CircleAlert:CheckCircle2;return <div className="panel border-primary/30 p-5"><div className="flex items-center gap-2 text-primary"><Icon className="size-5"/><span className="label-xs">AUTHORITATIVE DECISION</span></div><div className="mt-3 text-xl font-semibold">{reasoning.decision}</div><p className="mt-2 text-sm leading-6 text-muted-foreground">{reasoning.summary}</p></div>}
function Metric({label,value,sub}:{label:string;value:string;sub:string}){return <div className="panel p-5"><div className="label-xs">{label}</div><div className="mt-3 text-3xl font-semibold">{value}</div><div className="mt-1 text-xs text-muted-foreground">{sub}</div></div>}
function Overview({result}:{result:IntelligenceResult}){return <div className="space-y-6"><div><h2 className="font-medium">Match state</h2><p className="mt-1 text-sm text-muted-foreground">Recent results, scoring/conceding rates and venue performance are combined without assuming bookmaker prices are truth.</p></div><div className="grid gap-3 md:grid-cols-2"><TeamCard team={result.home} venue="HOME"/><TeamCard team={result.away} venue="AWAY"/></div><div><h3 className="label-xs">GOAL & BTTS OUTLOOK</h3><div className="mt-3 grid grid-cols-2 gap-3 sm:grid-cols-4">{["over0.5","over1.5","over2.5","over3.5"].map(k=><Metric key={k} label={k.replace("over","OVER ")} value={`${Math.round((result.totals[k]??0)*100)}%`} sub="model probability"/>)}</div></div><div className="rounded-md border border-border bg-muted/20 p-4 text-sm"><strong>BTTS:</strong> {Math.round(result.btts.yes*100)}% yes</div></div>}
function TeamCard({team,venue}:{team:IntelligenceResult["home"];venue:string}){return <div className="rounded-lg border border-border p-4"><div className="label-xs">{venue}</div><div className="mt-2 font-medium">{team.team}</div><div className="mt-4 grid grid-cols-4 gap-2 text-center text-xs"><div><b className="block text-base">{team.played}</b>GP</div><div><b className="block text-base">{team.wins}</b>W</div><div><b className="block text-base">{team.draws}</b>D</div><div><b className="block text-base">{team.losses}</b>L</div></div><div className="mt-4 text-xs text-muted-foreground">Goals {team.goalsFor}-{team.goalsAgainst} · venue win rate {Math.round(team.homeOrAwayRate*100)}%</div><div className="mt-3 flex gap-1">{team.recent.map((r,i)=><span key={`${r}-${i}`} className="grid size-6 place-items-center rounded bg-muted text-[10px]">{r}</span>)}</div></div>}
function Engines({result}:{result:IntelligenceResult}){const rows=[{name:"Goal-rate / Poisson",value:`λH ${(result.home.goalsFor/Math.max(1,result.home.played)).toFixed(2)} · λA ${(result.away.goalsFor/Math.max(1,result.away.played)).toFixed(2)}`},{name:"Recent form",value:`${result.home.points} home-side points · ${result.away.points} away-side points`},{name:"Venue",value:`${Math.round(result.home.homeOrAwayRate*100)}% home venue win rate · ${Math.round(result.away.homeOrAwayRate*100)}% away venue win rate`},{name:"BTTS",value:`${Math.round(result.btts.yes*100)}% yes`},{name:"1X2",value:`H ${Math.round(result.probabilities.home*100)}% · D ${Math.round(result.probabilities.draw*100)}% · A ${Math.round(result.probabilities.away*100)}%`}];return <div><h2 className="font-medium">Engine arena</h2><div className="mt-4 divide-y divide-border">{rows.map(r=><div key={r.name} className="flex flex-col gap-1 py-4 sm:flex-row sm:items-center sm:justify-between"><span className="text-sm font-medium">{r.name}</span><span className="text-sm text-muted-foreground">{r.value}</span></div>)}</div></div>}
function Evidence({result}:{result:IntelligenceResult}){return <div><div className="flex items-center gap-2"><Sparkles className="size-4 text-primary"/><h2 className="font-medium">Evidence ledger</h2></div><p className="mt-1 text-sm text-muted-foreground">Only evidence actually loaded into the model is shown here.</p><div className="mt-4 space-y-3">{result.evidence.map(x=><div key={x} className="rounded-md border border-border p-4 text-sm">{x}</div>)}</div><div className="mt-6 rounded-md border border-warning/30 bg-warning/5 p-4 text-sm"><strong>Missing layers:</strong> bookmaker odds, injuries, lineups, xG and live news are not fabricated.</div></div>}
function Reasoning({reasoning}:{reasoning:MatchReasoning}){return <div><h2 className="font-medium">Reasoning chain</h2><p className="mt-1 text-sm text-muted-foreground">Auditable synthesis between quantitative engines and any future AI narrative.</p><div className="mt-5 space-y-3">{reasoning.claims.map(c=><div key={c.id} className="rounded-md border border-border p-4"><div className="flex items-center justify-between"><span className={`label-xs ${c.signal==="SUPPORT"?"text-positive":c.signal==="CONTRADICTION"?"text-warning":"text-muted-foreground"}`}>{c.signal}</span><span className="text-xs text-muted-foreground">strength {Math.round(c.strength*100)}%</span></div><p className="mt-2 text-sm font-medium">{c.statement}</p><p className="mt-1 text-xs leading-5 text-muted-foreground">{c.evidence}</p></div>)}</div><div className="mt-6"><h3 className="label-xs">NEXT INTELLIGENCE QUESTIONS</h3><ul className="mt-3 space-y-2">{reasoning.questionsForNextLayer.map(q=><li key={q} className="text-sm text-muted-foreground">› {q}</li>)}</ul></div></div>}
function State({title,text,back}:{title:string;text:string;back?:boolean}){return <div className="grid min-h-screen place-items-center p-8"><div className="max-w-md text-center"><h1 className="text-2xl font-semibold">{title}</h1><p className="mt-2 text-sm text-muted-foreground">{text}</p>{back&&<Link to="/" className="button-primary mt-6 inline-flex">Return to search</Link>}</div></div>}
