import { useQuery } from "@tanstack/react-query";
import { Link } from "@tanstack/react-router";
import { AlertTriangle, RefreshCw } from "lucide-react";
import { runBatchAnalysis } from "@/lib/gfi/batch-analysis";

export function EngineArena(){
  const q=useQuery({queryKey:["engine-arena"],queryFn:()=>runBatchAnalysis({data:{limit:12,includeUpcoming:true}}),staleTime:5*60_000});
  return <div className="mx-auto max-w-7xl px-5 py-8 lg:px-10"><Link to="/" className="label-xs">← HOME</Link><header className="mt-7 border-b border-border pb-6"><div className="label-xs text-primary">MODEL GRAPH</div><h1 className="mt-2 text-3xl font-semibold">Engine Arena</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Every displayed match is produced by the same authoritative backend used by Match Intelligence and Batch.</p></header><div className="mt-6">{q.isLoading&&<div className="panel p-8 text-sm text-muted-foreground">Running the shared engine graph…</div>}{q.error&&<div className="panel p-8"><AlertTriangle className="size-5 text-warning"/><p className="mt-2 text-sm">Engine scan failed.</p><button onClick={()=>q.refetch()} className="mt-4 inline-flex items-center gap-2 rounded border border-border px-3 py-2 text-sm"><RefreshCw className="size-4"/> Retry</button></div>}{q.data&&<div className="grid gap-4">{q.data.map((row)=><div key={`${row.fixture.date}-${row.fixture.home}-${row.fixture.away}`} className="panel p-5"><div className="flex flex-wrap items-center justify-between gap-3"><div><b>{row.fixture.home} vs {row.fixture.away}</b><div className="mt-1 text-xs text-muted-foreground">{row.fixture.league} · {row.analysis.engines.length} active outputs · analysis {row.analysis.analysisVersion}</div></div><span className="label-xs">{row.analysis.decision}</span></div><div className="mt-4 grid gap-3 sm:grid-cols-2 lg:grid-cols-5">{row.analysis.engines.map((e)=><div key={e.id} className="border border-border p-3"><div className="label-xs">{e.id}</div><div className="metric mt-2">{e.probabilities?`${Math.round(Math.max(e.probabilities.home,e.probabilities.draw,e.probabilities.away)*100)}%`:e.confidence+"%"}</div><div className="mt-1 text-xs text-muted-foreground">{e.signal} · Q{e.quality}</div></div>)}</div></div>)}</div>}</div></div>;
}
