import { useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { Link } from "@tanstack/react-router";
import { RefreshCw, Play, Save, Trash2, CheckCircle2, AlertTriangle, BarChart3 } from "lucide-react";
import { loadWorkbench, rankBatch, simulateMatch, readLedger, savePrediction, settlePrediction, clearLedger, type Prediction, type ScoredFixture } from "@/lib/gfi/workbench";
import { analyzeMatch } from "@/lib/gfi/intelligence";

function Shell({eyebrow,title,children}:{eyebrow:string;title:string;children:React.ReactNode}) { return <div className="mx-auto max-w-7xl px-5 py-8 lg:px-10"><Link to="/" className="label-xs hover:text-foreground">← HOME</Link><header className="mt-7 border-b border-border pb-6"><div className="label-xs text-primary">{eyebrow}</div><h1 className="mt-2 text-3xl font-semibold tracking-tight">{title}</h1></header><div className="mt-6">{children}</div></div> }
function LoadState({isLoading,error,onRetry}:{isLoading:boolean;error:unknown;onRetry:()=>void}) { if(isLoading) return <div className="panel p-8 text-sm text-muted-foreground">Loading free football data…</div>; if(error) return <div className="panel p-8"><AlertTriangle className="size-5 text-warning"/><p className="mt-3 text-sm">The free results feed could not be loaded.</p><button onClick={onRetry} className="mt-4 rounded-md border border-border px-3 py-2 text-sm">Retry</button></div>; return null }
const pct=(n:number)=>`${(n*100).toFixed(1)}%`;

export function BatchModule(){
 const q=useQuery({queryKey:["workbench"],queryFn:loadWorkbench,staleTime:30*60_000});
 const [limit,setLimit]=useState(10); const [selected,setSelected]=useState<ScoredFixture|null>(null);
 const rows=useMemo(()=>q.data?rankBatch(q.data,limit):[],[q.data,limit]);
 return <Shell eyebrow="PORTFOLIO ANALYSIS" title="Batch Intelligence"><LoadState isLoading={q.isLoading} error={q.error} onRetry={()=>q.refetch()}/>{q.data&&<><div className="mb-5 flex flex-wrap items-center gap-2"><span className="label-xs">RANK</span>{[10,20,24].map(n=><button key={n} onClick={()=>setLimit(n)} className={`rounded-md border px-3 py-1.5 text-xs ${limit===n?'border-primary text-primary':'border-border'}`}>{n}</button>)}<button onClick={()=>q.refetch()} className="ml-auto rounded-md border border-border p-2"><RefreshCw className="size-4"/></button></div><div className="grid gap-5 lg:grid-cols-[1fr_360px]"><div className="panel overflow-hidden"><div className="grid grid-cols-[40px_1fr_90px_90px_90px] gap-2 border-b border-border px-4 py-3 label-xs"><span>#</span><span>FIXTURE</span><span>EDGE</span><span>CONF</span><span>QUALITY</span></div>{rows.map((r,i)=><button key={`${r.home}-${r.away}-${r.date}`} onClick={()=>setSelected(r)} className={`grid w-full grid-cols-[40px_1fr_90px_90px_90px] gap-2 border-b border-border px-4 py-4 text-left hover:bg-muted/30 ${selected===r?'bg-muted/40':''}`}><span className="metric text-muted-foreground">{i+1}</span><span><b>{r.home}</b> <span className="text-muted-foreground">vs</span> <b>{r.away}</b><small className="mt-1 block text-muted-foreground">{r.league} · {r.date}</small></span><span className="metric">{r.score.toFixed(1)}</span><span className="metric">{r.confidence}</span><span className="metric">{r.quality}</span></button>)}</div><div className="panel p-5">{selected?<><div className="label-xs">SELECTED</div><h2 className="mt-2 text-lg font-semibold">{selected.home} vs {selected.away}</h2><p className="mt-1 text-xs text-muted-foreground">{selected.league} · {selected.verdict}</p><div className="mt-5 grid grid-cols-3 gap-2">{[["H",selected.result.probabilities.home],["D",selected.result.probabilities.draw],["A",selected.result.probabilities.away]].map(([k,v])=><div key={k as string} className="rounded-md border border-border p-3"><div className="label-xs">{k}</div><div className="metric mt-1 text-lg">{pct(v as number)}</div></div>)}</div><div className="mt-4 text-sm text-muted-foreground">{selected.result.warnings.join(" ")}</div><button onClick={()=>savePrediction({fixture:selected,probabilities:selected.result.probabilities,totals:selected.result.totals,btts:selected.result.btts,verdict:selected.verdict,confidence:selected.confidence,quality:selected.quality,modelVersion:"free-v1"})} className="mt-5 inline-flex items-center gap-2 rounded-md bg-primary px-3 py-2 text-sm text-primary-foreground"><Save className="size-4"/> Save prediction</button></>:<div className="text-sm text-muted-foreground">Select a ranked fixture to inspect its evidence and save a prediction.</div>}</div></div></>}</Shell>
}

export function SimulationModule(){
 const q=useQuery({queryKey:["workbench"],queryFn:loadWorkbench,staleTime:30*60_000}); const [idx,setIdx]=useState(0); const [runs,setRuns]=useState(10000); const [result,setResult]=useState<ReturnType<typeof simulateMatch>|null>(null);
 const fixtures=useMemo(()=>q.data?rankBatch(q.data,12):[],[q.data]); const f=fixtures[idx]; const all=q.data?.find(g=>g.league===f?.league)?.matches??[];
 return <Shell eyebrow="SCENARIO ENGINE" title="Simulation Lab"><LoadState isLoading={q.isLoading} error={q.error} onRetry={()=>q.refetch()}/>{f&&<><div className="panel p-4 flex flex-wrap gap-3 items-center"><select value={idx} onChange={e=>{setIdx(+e.target.value);setResult(null)}} className="h-10 rounded-md border border-border bg-background px-3 text-sm flex-1">{fixtures.map((x,i)=><option key={i} value={i}>{x.home} vs {x.away} · {x.league}</option>)}</select><select value={runs} onChange={e=>setRuns(+e.target.value)} className="h-10 rounded-md border border-border bg-background px-3 text-sm"><option value={5000}>5,000 worlds</option><option value={10000}>10,000 worlds</option><option value={25000}>25,000 worlds</option></select><button onClick={()=>setResult(simulateMatch(f,all,runs))} className="inline-flex items-center gap-2 rounded-md bg-primary px-4 py-2 text-sm text-primary-foreground"><Play className="size-4"/> Run simulation</button></div>{result&&<div className="mt-5 grid gap-5 lg:grid-cols-[1fr_360px]"><div className="panel p-5"><div className="label-xs">{result.iterations.toLocaleString()} MONTE CARLO WORLDS</div><div className="mt-5 grid grid-cols-2 gap-3 md:grid-cols-4">{[["HOME",result.homeWin],["DRAW",result.draw],["AWAY",result.awayWin],["BTTS",result.btts]].map(([k,v])=><div key={k as string} className="rounded-md border border-border p-4"><div className="label-xs">{k}</div><div className="metric mt-2 text-2xl">{pct(v as number)}</div></div>)}</div><div className="mt-6 grid grid-cols-3 gap-3">{[["O1.5",result.over15],["O2.5",result.over25],["O3.5",result.over35]].map(([k,v])=><div key={k as string} className="border-t border-border pt-3"><div className="label-xs">{k}</div><div className="metric mt-1">{pct(v as number)}</div></div>)}</div></div><div className="panel p-5"><div className="label-xs">MOST COMMON SCORELINES</div>{result.topScores.map(s=><div key={s.score} className="mt-3 flex items-center gap-3"><span className="metric w-10">{s.score}</span><div className="h-2 flex-1 rounded-full bg-muted overflow-hidden"><div className="h-full bg-primary" style={{width:`${Math.max(2,s.probability*100)}%`}}/></div><span className="metric text-xs">{pct(s.probability)}</span></div>)}</div></div>}</>}</Shell>
}

export function EnginesModule(){
 const q=useQuery({queryKey:["workbench"],queryFn:loadWorkbench,staleTime:30*60_000}); const rows=useMemo(()=>q.data?rankBatch(q.data,10):[],[q.data]);
 return <Shell eyebrow="MODEL COMPARISON" title="Engine Arena"><LoadState isLoading={q.isLoading} error={q.error} onRetry={()=>q.refetch()}/>{rows.length>0&&<div className="grid gap-4">{rows.map(r=>{const x=r.result;const strength=(x.home.points/Math.max(1,x.home.played))-(x.away.points/Math.max(1,x.away.played));const engines=[{name:"Goal-rate",value:Math.max(x.probabilities.home,x.probabilities.away),detail:"Poisson-style scoring distribution"},{name:"Form",value:0.5+strength*.08,detail:"Recent points and results"},{name:"Venue",value:(x.home.homeOrAwayRate+x.away.homeOrAwayRate)/2,detail:"Home/away win-rate signal"},{name:"Consensus",value:Math.max(x.probabilities.home,x.probabilities.draw,x.probabilities.away),detail:"Combined decision probability"}];return <div key={`${r.home}${r.away}${r.date}`} className="panel p-5"><div className="flex items-start justify-between"><div><h2 className="font-semibold">{r.home} <span className="text-muted-foreground">vs</span> {r.away}</h2><p className="mt-1 text-xs text-muted-foreground">{r.league} · {r.verdict}</p></div><span className="label-xs">QUALITY {r.quality}</span></div><div className="mt-5 grid gap-3 md:grid-cols-4">{engines.map(e=><div key={e.name} className="rounded-md border border-border p-4"><div className="label-xs">{e.name}</div><div className="metric mt-2 text-xl">{pct(Math.max(0,Math.min(1,e.value)))}</div><p className="mt-1 text-xs text-muted-foreground">{e.detail}</p></div>)}</div></div>})}</div>}</Shell>
}

export function EvidenceModule(){
 const q=useQuery({queryKey:["workbench"],queryFn:loadWorkbench,staleTime:30*60_000}); const rows=useMemo(()=>q.data?rankBatch(q.data,12):[],[q.data]);
 return <Shell eyebrow="SOURCE GRAPH" title="Evidence Intelligence"><LoadState isLoading={q.isLoading} error={q.error} onRetry={()=>q.refetch()}/>{rows.length>0&&<div className="panel overflow-hidden"><div className="border-b border-border p-5 text-sm text-muted-foreground">Evidence is source-labelled. FREE MODE currently has completed public results; unavailable domains are explicitly marked missing.</div>{rows.map(r=><div key={`${r.home}${r.away}${r.date}`} className="border-b border-border p-5 last:border-0"><div className="flex flex-wrap justify-between gap-3"><div><b>{r.home} vs {r.away}</b><span className="ml-2 text-xs text-muted-foreground">{r.league}</span></div><span className="label-xs">MODEL {r.result.quality}</span></div><div className="mt-4 grid gap-3 md:grid-cols-3">{r.result.evidence.map((e,i)=><div key={i} className="rounded-md border border-border p-3 text-xs text-muted-foreground"><CheckCircle2 className="mb-2 size-4 text-positive"/>{e}</div>)}</div><div className="mt-3 rounded-md border border-warning/30 bg-warning/5 p-3 text-xs text-muted-foreground"><AlertTriangle className="mr-2 inline size-3 text-warning"/>Missing in FREE MODE: live news, injuries, confirmed lineups, xG provider and bookmaker odds.</div></div>)}</div>}</Shell>
}

export function PredictionsModule(){
 const [,force]=useState(0); const ledger=readLedger(); const settled=ledger.filter(x=>x.status==='SETTLED'); const wins=settled.filter(x=>x.correct).length;
 return <Shell eyebrow="IMMUTABLE LEDGER" title="Prediction History"><div className="mb-5 grid grid-cols-2 gap-3 md:grid-cols-4">{[["TOTAL",ledger.length],["OPEN",ledger.filter(x=>x.status==='OPEN').length],["SETTLED",settled.length],["HIT RATE",settled.length?`${((wins/settled.length)*100).toFixed(1)}%`:"—"]].map(([k,v])=><div key={k as string} className="panel p-4"><div className="label-xs">{k}</div><div className="metric mt-2 text-xl">{v}</div></div>)}</div><div className="mb-4 flex justify-end"><button onClick={()=>{clearLedger();force(x=>x+1)}} className="inline-flex items-center gap-2 rounded-md border border-border px-3 py-2 text-xs"><Trash2 className="size-3"/> Clear ledger</button></div><div className="panel overflow-hidden">{ledger.length===0?<div className="p-8 text-sm text-muted-foreground">No predictions saved yet. Save one from Batch Intelligence.</div>:ledger.map(p=><PredictionRow key={p.id} p={p} onSettle={()=>force(x=>x+1)}/>)}</div></Shell>
}
function PredictionRow({p,onSettle}:{p:Prediction;onSettle:()=>void}){ const [out,setOut]=useState<"H"|"D"|"A">("H"); return <div className="border-b border-border p-5 last:border-0"><div className="flex flex-wrap justify-between gap-3"><div><b>{p.fixture.home} vs {p.fixture.away}</b><div className="mt-1 text-xs text-muted-foreground">{new Date(p.createdAt).toLocaleString()} · {p.modelVersion}</div></div><span className={`label-xs ${p.correct===true?'text-positive':p.correct===false?'text-destructive':''}`}>{p.status}{p.status==='SETTLED'?` · ${p.correct?'CORRECT':'WRONG'}`:''}</span></div><div className="mt-4 grid grid-cols-3 gap-2">{[["H",p.probabilities.home],["D",p.probabilities.draw],["A",p.probabilities.away]].map(([k,v])=><div key={k as string} className="border border-border p-3"><div className="label-xs">{k}</div><div className="metric mt-1">{pct(v as number)}</div></div>)}</div>{p.status==='OPEN'&&<div className="mt-4 flex gap-2"><select value={out} onChange={e=>setOut(e.target.value as any)} className="rounded-md border border-border bg-background px-2 text-xs"><option value="H">Home</option><option value="D">Draw</option><option value="A">Away</option></select><button onClick={()=>{settlePrediction(p.id,out);onSettle()}} className="rounded-md bg-primary px-3 py-2 text-xs text-primary-foreground">Settle</button></div>}</div> }

export function AuditModule(){ const ledger=readLedger(); const settled=ledger.filter(x=>x.status==='SETTLED'); return <Shell eyebrow="LEARNING LOOP" title="Post-Match Audit">{settled.length===0?<div className="panel p-8 text-sm text-muted-foreground">No settled predictions yet. Settle predictions in Prediction History and the audit will automatically calculate the error profile.</div>:<><div className="grid gap-4 md:grid-cols-4">{(()=>{const wins=settled.filter(x=>x.correct).length;const brier=settled.reduce((s,p)=>{const actual=p.outcome==='H'?p.probabilities.home:p.outcome==='D'?p.probabilities.draw:p.probabilities.away;return s+(1-actual)**2},0)/settled.length;return [["SETTLED",settled.length],["CORRECT",wins],["HIT RATE",pct(wins/settled.length)],["MEAN LOSS",brier.toFixed(3)]]})().map(([k,v])=><div key={k as string} className="panel p-4"><div className="label-xs">{k}</div><div className="metric mt-2 text-xl">{v}</div></div>)}</div><div className="mt-5 panel p-5"><div className="label-xs">ERROR DECOMPOSITION</div>{settled.map(p=><div key={p.id} className="mt-4 grid gap-3 border-b border-border pb-4 last:border-0 md:grid-cols-[1fr_120px_120px_1fr]"><div><b>{p.fixture.home} vs {p.fixture.away}</b><div className="text-xs text-muted-foreground">{p.verdict}</div></div><span className="label-xs">ACTUAL {p.outcome}</span><span className={p.correct?'text-positive':'text-destructive'}>{p.correct?'MODEL HIT':'MODEL MISS'}</span><span className="text-xs text-muted-foreground">Confidence {p.confidence}; data quality {p.quality}. {p.correct?'Signal survived settlement.':'Review variance, missing evidence and model calibration.'}</span></div>)}</div></>}</Shell> }
