import { useState } from "react";
import { useMutation } from "@tanstack/react-query";
import { Link } from "@tanstack/react-router";
import { Play, ShieldCheck } from "lucide-react";
import { runBacktest, type BacktestReport } from "@/lib/gfi/model-lab";

export function ModelLab(){
  const [report,setReport]=useState<BacktestReport|null>(null);
  const mutation=useMutation({mutationFn:()=>runBacktest({data:{limit:48}}),onSuccess:setReport});
  return <div className="mx-auto max-w-7xl px-5 py-8 lg:px-10"><Link to="/" className="label-xs">← HOME</Link><header className="mt-7 border-b border-border pb-6"><div className="label-xs text-primary">LEARNING LOOP</div><h1 className="mt-2 text-3xl font-semibold">Model Lab</h1><p className="mt-2 max-w-2xl text-sm text-muted-foreground">Run a chronological out-of-sample check on the same authoritative engine graph used by the live product.</p></header><div className="mt-6 grid gap-5 lg:grid-cols-[1fr_360px]"><div className="panel p-5"><div className="flex items-center gap-3"><ShieldCheck className="size-5 text-primary"/><div><div className="font-medium">Backtest harness</div><div className="text-xs text-muted-foreground">Past match only — the fixture being scored is excluded from its historical evidence.</div></div></div><button disabled={mutation.isPending} onClick={()=>mutation.mutate()} className="mt-5 inline-flex items-center gap-2 rounded bg-primary px-4 py-2 text-sm text-primary-foreground"><Play className="size-4"/>{mutation.isPending?'Running…':'Run 48-match backtest'}</button>{mutation.error&&<p className="mt-4 text-sm text-destructive">{String(mutation.error)}</p>}</div><div className="panel p-5">{report?<><div className="label-xs">RESULT</div><div className="mt-4 grid grid-cols-2 gap-3">{[['HIT RATE',`${(report.hitRate*100).toFixed(1)}%`],['BRIER',report.brier.toFixed(3)],['LOG LOSS',report.logLoss.toFixed(3)],['QUALITY',report.averageQuality.toFixed(0)],['CONFIDENCE',report.averageConfidence.toFixed(0)],['ENGINES',report.enginesObserved.length]].map(([k,v])=><div key={k} className="border border-border p-3"><div className="label-xs">{k}</div><div className="metric mt-1">{v}</div></div>)}</div><p className="mt-4 text-xs text-muted-foreground">Evaluated {report.evaluated} of {report.fixtures} completed fixtures. Active engine outputs: {report.enginesObserved.join(', ')}.</p></>:<p className="text-sm text-muted-foreground">No backtest has been run yet.</p>}</div></div></div>;
}
