import { createServerFn } from "@tanstack/react-start";
import type { MatchRow } from "./intelligence";

type Source={name:string;url:string;region:string;priority:number};
const GH="https://api.github.com", RAW="https://raw.githubusercontent.com/openfootball";
const EXCLUDED=new Set(["awesome-football","openfootball.github.io","quick-starter","sandbox","spec","v0-format","opendata-theme"]);
async function getJson(url:string){const c=new AbortController(),t=setTimeout(()=>c.abort(),12000);try{const r=await fetch(url,{signal:c.signal,headers:{Accept:"application/vnd.github+json","User-Agent":"Global-Football-Intelligence/1.0"}});if(!r.ok)throw new Error(`HTTP ${r.status}`);return await r.json()}finally{clearTimeout(t)}}
export const discoverOpenFootballUniverse=createServerFn({method:"GET"}).handler(async():Promise<Source[]>=>{const repos=await getJson(`${GH}/orgs/openfootball/repos?per_page=100&sort=updated`) as any[];const out:Source[]=[];for(const repo of repos){const name=String(repo.name??"");if(!name||EXCLUDED.has(name)||repo.archived)continue;const tree=await getJson(`${GH}/repos/openfootball/${name}/git/trees/${repo.default_branch??"master"}?recursive=1`).catch(()=>null);for(const f of (tree?.tree??[]).filter((x:any)=>x.type==="blob"&&/\.json$/i.test(String(x.path??""))).slice(0,200)){out.push({name:`openfootball/${name}:${f.path}`,url:`${RAW}/${name}/${repo.default_branch??"master"}/${f.path}`,region:name,priority:name==="world"?1:2})}}return out.sort((a,b)=>a.priority-b.priority).slice(0,5000)});
function parse(payload:any,source:string):MatchRow[]{const arr=Array.isArray(payload?.matches)?payload.matches:Array.isArray(payload)?payload:[];return arr.flatMap((x:any,i:number)=>{const date=String(x?.date??"").slice(0,10),home=String(x?.team1??x?.home??"").trim(),away=String(x?.team2??x?.away??"").trim();if(!date||!home||!away)return[];const ft=Array.isArray(x?.score?.ft)?x.score.ft:[],hg=ft[0]==null?undefined:Number(ft[0]),ag=ft[1]==null?undefined:Number(ft[1]);return[{date,time:typeof x?.time==="string"?x.time.slice(0,5):undefined,home,away,hg:Number.isFinite(hg)?hg:undefined,ag:Number.isFinite(ag)?ag:undefined,result:Number.isFinite(hg)&&Number.isFinite(ag)?(hg!>ag!?"H":hg===ag?"D":"A"):undefined,league:String(payload?.name??source),source:"openfootball",sourceId:`${source}#${i}`}]})}
export const harvestOpenFootballUniverse=createServerFn({method:"POST"}).validator((input:{limit?:number})=>input).handler(async({data})=>{const sources=await discoverOpenFootballUniverse(),sample=sources.slice(0,Math.max(10,Math.min(data.limit??120,sources.length))),rows:MatchRow[]=[];for(const s of sample){try{const r=await fetch(s.url,{headers:{Accept:"application/json"}});if(r.ok)rows.push(...parse(await r.json(),s.name))}catch{}}return{sourcesDiscovered:sources.length,sourcesSampled:sample.length,matches:rows,distinctTeams:new Set(rows.flatMap(r=>[r.home,r.away])).size,distinctCompetitions:new Set(rows.map(r=>r.league??"Worldwide Football")).size}});
