/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuditRouteImport } from './routes/audit'
import { Route as BatchRouteImport } from './routes/batch'
import { Route as EnginesRouteImport } from './routes/engines'
import { Route as EvidenceRouteImport } from './routes/evidence'
import { Route as ModelLabRouteImport } from './routes/model-lab'
import { Route as PredictionsRouteImport } from './routes/predictions'
import { Route as SimulationRouteImport } from './routes/simulation'
import { Route as SystemRouteImport } from './routes/system'
import { Route as MatchMatchIdRouteImport } from './routes/match.$matchId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditRoute = AuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const BatchRoute = BatchRouteImport.update({
  id: '/batch',
  path: '/batch',
  getParentRoute: () => rootRouteImport,
} as any)
const EnginesRoute = EnginesRouteImport.update({
  id: '/engines',
  path: '/engines',
  getParentRoute: () => rootRouteImport,
} as any)
const EvidenceRoute = EvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => rootRouteImport,
} as any)
const ModelLabRoute = ModelLabRouteImport.update({
  id: '/model-lab',
  path: '/model-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const PredictionsRoute = PredictionsRouteImport.update({
  id: '/predictions',
  path: '/predictions',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulationRoute = SimulationRouteImport.update({
  id: '/simulation',
  path: '/simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const SystemRoute = SystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchMatchIdRoute = MatchMatchIdRouteImport.update({
  id: '/match/$matchId',
  path: '/match/$matchId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/batch': typeof BatchRoute
  '/engines': typeof EnginesRoute
  '/evidence': typeof EvidenceRoute
  '/model-lab': typeof ModelLabRoute
  '/predictions': typeof PredictionsRoute
  '/simulation': typeof SimulationRoute
  '/system': typeof SystemRoute
  '/match/$matchId': typeof MatchMatchIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/batch': typeof BatchRoute
  '/engines': typeof EnginesRoute
  '/evidence': typeof EvidenceRoute
  '/model-lab': typeof ModelLabRoute
  '/predictions': typeof PredictionsRoute
  '/simulation': typeof SimulationRoute
  '/system': typeof SystemRoute
  '/match/$matchId': typeof MatchMatchIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/audit': typeof AuditRoute
  '/batch': typeof BatchRoute
  '/engines': typeof EnginesRoute
  '/evidence': typeof EvidenceRoute
  '/model-lab': typeof ModelLabRoute
  '/predictions': typeof PredictionsRoute
  '/simulation': typeof SimulationRoute
  '/system': typeof SystemRoute
  '/match/$matchId': typeof MatchMatchIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/audit'
    | '/batch'
    | '/engines'
    | '/evidence'
    | '/model-lab'
    | '/predictions'
    | '/simulation'
    | '/system'
    | '/match/$matchId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/audit'
    | '/batch'
    | '/engines'
    | '/evidence'
    | '/model-lab'
    | '/predictions'
    | '/simulation'
    | '/system'
    | '/match/$matchId'
  id:
    | '__root__'
    | '/'
    | '/audit'
    | '/batch'
    | '/engines'
    | '/evidence'
    | '/model-lab'
    | '/predictions'
    | '/simulation'
    | '/system'
    | '/match/$matchId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuditRoute: typeof AuditRoute
  BatchRoute: typeof BatchRoute
  EnginesRoute: typeof EnginesRoute
  EvidenceRoute: typeof EvidenceRoute
  ModelLabRoute: typeof ModelLabRoute
  PredictionsRoute: typeof PredictionsRoute
  SimulationRoute: typeof SimulationRoute
  SystemRoute: typeof SystemRoute
  MatchMatchIdRoute: typeof MatchMatchIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit': {
      id: '/audit'
      path: '/audit'
      fullPath: '/audit'
      preLoaderRoute: typeof AuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/batch': {
      id: '/batch'
      path: '/batch'
      fullPath: '/batch'
      preLoaderRoute: typeof BatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/engines': {
      id: '/engines'
      path: '/engines'
      fullPath: '/engines'
      preLoaderRoute: typeof EnginesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evidence': {
      id: '/evidence'
      path: '/evidence'
      fullPath: '/evidence'
      preLoaderRoute: typeof EvidenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/model-lab': {
      id: '/model-lab'
      path: '/model-lab'
      fullPath: '/model-lab'
      preLoaderRoute: typeof ModelLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/predictions': {
      id: '/predictions'
      path: '/predictions'
      fullPath: '/predictions'
      preLoaderRoute: typeof PredictionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulation': {
      id: '/simulation'
      path: '/simulation'
      fullPath: '/simulation'
      preLoaderRoute: typeof SimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/system': {
      id: '/system'
      path: '/system'
      fullPath: '/system'
      preLoaderRoute: typeof SystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match/$matchId': {
      id: '/match/$matchId'
      path: '/match/$matchId'
      fullPath: '/match/$matchId'
      preLoaderRoute: typeof MatchMatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuditRoute: AuditRoute,
  BatchRoute: BatchRoute,
  EnginesRoute: EnginesRoute,
  EvidenceRoute: EvidenceRoute,
  ModelLabRoute: ModelLabRoute,
  PredictionsRoute: PredictionsRoute,
  SimulationRoute: SimulationRoute,
  SystemRoute: SystemRoute,
  MatchMatchIdRoute: MatchMatchIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
